name: "Deploy to Yak"

on:
  push:
    tags:
      -"*"
jobs:
  build:
    runs-on: [ windows-2019 ]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install IronPython
      run: choco install ironpython --version=2.7.12
    - name: Build Grasshopper Plugin
      run: ipy grasshopper-plugin/build_module.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tapir Grasshopper Plugin
        path: grasshopper-plugin/bin/tapir_gh.ghpy
    - name: debug
      run: echo "${{ github.ref_name }}"
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        artifacts: grasshopper-plugin/bin/tapir_gh.ghpy
        draft: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v3.2.0
      - name: setup yak
        uses: paramdigma/setup-yak@1.0.0
        with:
          token: ${{secrets.YAK_TOKEN}}
      - name: Create Yak manifest
        run: |
          yak spec
          Add-Content manifest.yml "icon: branding/logo/png/tapir_logo_black_512.png"
          Add-Content manifest.yml "version: ${{ github.ref_name }}"
        working-directory: grasshopper-plugin\bin
